### ISSUE TITLE
resource.error: (1, 'Operation not permitted') when trying to run docker image

### ISSUE THREAD

**Issue by rbrooklyn** [kerberos-io/docker#25]
OS is Ubuntu 20.04.
Running on a Raspberry pi 4 4GB.

Unfortunately it seems the docker image is doing something docker or Ubuntu isn't allowing. When running sudo docker run -p 80:80 -p 8889:8889 kerberos/kerberos the following output is observed and the container stops:

> Config files are available.
Config files are available.
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==3.3.1', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 365, in main
    go(options)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 375, in go
    d.main()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 70, in main
    rlimit_messages = self.options.set_rlimits()
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1372, in set_rlimits
    soft, hard = resource.getrlimit(res)
resource.error: (1, 'Operation not permitted')

**Comment by cedricve** [comment]
hmmm @rbrooklyn do you have any update on this?

**Comment by rbrooklyn** [comment]
Only that it's probably still broken, unless an update has landed since I raised the issue.

The only way to get this working is to run the container privileged, which is obviously far from ideal.

**Comment by cedricve** [comment]
I believe this is because the OS you are using.. maybe something have to change within the dockerfile. It works just fine on other OSes. Interested to get this working.

Kind regards,
Verstraeten Cédric

**Comment by chevli** [comment]
I had to run this using the `--privileged` flag to get this working on my RP4 running Ubuntu 20.04. I hope that helps.
